In [ ]:
'В people.*.csv найти номера карт, сумма цифр в которых кратна 7. Выполнить задание с использованием Dask, распараллелив процесс обработки данных. Выполнить задание с использованием Dask (корректным!), распараллелив процесс обработки данных (использование Dask должно приводить к истинной параллельной обработке данных).'

In [9]:
import dask.dataframe as dd

dask_table = dd.read_csv('people.0.csv')
append = dd.read_csv('people.1.csv')
dask_table.append(append)
append = dd.read_csv('people.2.csv')
dask_table.append(append)
dask_table.set_index('Unnamed: 0')

Dask DataFrame Structure:
                 age occupation telephone first_name last_name    addr    city    card expiration-date
npartitions=1
0              int64     object    object     object    object  object  object  object          object
999              ...        ...       ...        ...       ...     ...     ...     ...             ...
Dask Name: sort_index, 3 tasks

Dask Series Structure:
npartitions=1
    object
       ...
Name: card, dtype: object
Dask Name: getitem, 2 tasks

In [2]:
dask_table.filter(lambda x: sum([int(i) for i in x['card']])%7 == 0).compute()

0      5438 1968 9922 9337
1        3769 395661 41045
2      2657 4280 9607 4252
3        3454 218578 39569
4      4994 8117 4888 3147
              ...
995    2550 1249 3872 7243
996    2665 1829 8085 1511
997    5342 4373 8149 9102
998      3757 857041 49817
999      3426 257684 04932
Name: card, Length: 1000, dtype: object

In [20]:
cards = dask_table.card.to_bag()
cards.filter(lambda x: sum([int(i) for i in x.replace(' ', '')])%7 == 0).compute()

['2718 8407 9504 4344',
 '3435 949578 19046',
 '3769 780398 39694',
 '4904 9489 9196 8990',
 '3770 280012 98351',
 '4165 0964 6721 5993',
 '3752 924034 42130',
 '3445 002229 53485',
 '3441 346673 96768',
 '4159 9083 9046 9539',
 '5111 3234 7614 9126',
 '3725 548893 16333',
 '4956 4349 4135 8928',
 '3412 453257 93924',
 '3728 445477 44434',
 '5330 3257 8798 8493',
 '3709 975224 23721',
 '4667 7462 9683 6244',
 '4234 7357 2564 7524',
 '4754 5453 3225 7025',
 '4299 8414 5501 5213',
 '4531 4073 1013 5642',
 '4772 8748 9435 4964',
 '5208 9530 2556 1050',
 '3477 419489 96724',
 '4718 2497 3824 8978',
 '3717 322628 12570',
 '5133 2059 7627 1829',
 '3412 597679 10896',
 '5397 9489 4937 9838',
 '4086 6613 6351 2748',
 '5569 7213 3820 3808',
 '3713 679956 13647',
 '3462 871060 67974',
 '2488 2314 5828 2553',
 '4756 5079 3629 4307',
 '4869 0310 3101 0983',
 '4835 4356 8592 6108',
 '3412 569421 43039',
 '5182 1938 7688 5940',
 '4172 1079 8371 5530',
 '5170 6263 8610 2169',
 '4604 9165 9705 9129',
 '5261 2238 8982 3549',
 '4472 1951 7505 8766',
 '2336 4224 9659 5809',
 '3713 746025 62316',
 '5468 8291 5868 4908',
 '5414 7663 1139 8320',
 '2349 9733 8431 3288',
 '2270 2496 9220 8012',
 '2487 9232 4453 1779',
 '4051 1507 0832 4200',
 '4494 4663 1485 9818',
 '4189 4554 2493 7408',
 '4810 4965 8344 0518',
 '4969 5604 6420 9695',
 '4590 0327 0690 6568',
 '4247 1448 7916 8129',
 '3415 538482 34668',
 '2645 7557 3992 9756',
 '3780 190223 06447',
 '5370 1645 8403 9528',
 '4193 7583 1016 9893',
 '4070 3079 0758 4797',
 '4205 2213 0663 1232',
 '3498 842214 33813',
 '2447 8806 1979 5653',
 '3458 373515 40967',
 '2369 6797 9790 3095',
 '3721 500349 15655',
 '4189 2673 0268 6951',
 '5185 8121 2234 1229',
 '4973 6126 5980 4659',
 '2260 6694 1899 2510',
 '3707 156983 17240',
 '2484 7084 7596 9605',
 '3787 493148 01339',
 '3400 816766 79391',
 '4883 9752 5393 1692',
 '5529 0609 3697 0628',
 '4111 1583 2858 6593',
 '2611 0953 7871 9121',
 '2378 3918 8806 9138',
 '3777 248227 66887',
 '3414 389106 69423',
 '3411 725320 80517',
 '2445 7590 5847 5732',
 '3462 412616 85195',
 '4769 7542 4504 7175',
 '4293 3587 9663 8799',
 '2363 4292 3416 8548',
 '2345 4972 0056 9000',
 '3745 644852 96993',
 '2545 4053 8180 5398',
 '5203 1394 5182 7497',
 '2228 3102 8803 3579',
 '4649 7305 6682 4661',
 '3443 299884 39202',
 '4286 1343 6129 0491',
 '2452 5677 0889 2291',
 '3446 253157 96267',
 '3706 557978 35041',
 '4224 5584 2086 3028',
 '4299 6235 6467 2302',
 '3487 790399 34765',
 '3406 103190 42565',
 '4682 5099 8087 6327',
 '2513 2088 2712 0440',
 '4845 8969 5422 6561',
 '3794 196139 34657',
 '3723 079539 48980',
 '5282 7024 2452 7983',
 '4640 6967 5842 7259',
 '4604 6387 0751 3916',
 '3794 330611 17731',
 '4764 5449 2601 5848',
 '4404 2130 9266 9913',
 '3424 942040 43550',
 '3453 549410 20153',
 '3449 938535 65670',
 '2575 1301 9008 2418',
 '3740 561320 45790',
 '3763 874949 71655',
 '5599 8657 0187 2667',
 '3783 850273 24119',
 '3460 686148 01959',
 '5433 6553 9698 4061',
 '5438 6794 2587 5400',
 '4541 2747 2457 4545',
 '2409 5477 3924 7545',
 '2283 7766 3357 1368',
 '4886 1196 4187 7815',
 '5245 9124 2982 0442',
 '2646 0593 6303 7054',
 '3722 944319 26988',
 '3430 344399 29881',
 '4653 4912 2802 8711',
 '4691 1710 1982 5178',
 '5327 1022 2273 9004']